# Generated by Django 4.2.1 on 2023-05-25 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_project_direction_project_floors_project_off_plan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='off_plan',
        ),
    ]
