# Generated by Django 4.2.1 on 2023-05-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_remove_project_off_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
