# Generated by Django 4.2.1 on 2023-05-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_project_off_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitiescategory',
            name='category',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
