# Generated by Django 4.2.1 on 2023-05-26 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_project_beach_distance_project_beach_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='beach_distance',
        ),
    ]
