# Generated by Django 4.2.1 on 2023-05-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_remove_project_beach_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='beach_distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
