# Generated by Django 4.2.1 on 2023-05-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_project_beach_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='photo_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
