# Generated by Django 4.2.1 on 2023-05-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_project_photo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='photo_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
