# Generated by Django 4.2.1 on 2023-05-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_developer_photo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.CharField(blank=True, choices=[('Studio', 'Studio'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14')], null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='bold_property',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='featured_property',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='for_rent_occupation_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='for_sale_occupation_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='furnishing',
            field=models.CharField(blank=True, choices=[('unfurnished', 'Unfurnished'), ('fully_furnished', 'Fully Furnished'), ('partly_furnished', 'Partly Furnished'), ('bare_shell', 'Bare Shell'), ('negotiable', 'Negotiable')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='hidden_private_info_form',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='listing_title_for_rent',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='listing_title_for_sale',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='listing_type',
            field=models.CharField(blank=True, choices=[('sell', 'Sell'), ('rent', 'Rent'), ('sell_rent', 'Sell&Rent')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='num_of_parking_spaces',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner_info_display',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner_social_accounts',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='ownership_type',
            field=models.CharField(blank=True, choices=[('foreign_quota', 'Foreign Quota'), ('thai_quota', 'Thai Quota'), ('leasehold', 'Leasehold'), ('company', 'Company')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='photos',
            field=models.ManyToManyField(blank=True, null=True, related_name='property_photos', to='property.photo'),
        ),
        migrations.AlterField(
            model_name='property',
            name='project_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_size',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(blank=True, choices=[('house', 'House'), ('villa', 'Villa'), ('condo', 'Condo'), ('apartment', 'Apartment'), ('townhouse', 'Townhouse'), ('land', 'Land'), ('shophouse', 'Shophouse')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='purchase_year_month',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='rental_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='sales_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='unit_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='unit_view',
            field=models.CharField(blank=True, choices=[('blocked_view', 'Blocked View'), ('360_views', '360° Views'), ('city_view', 'City View'), ('pool_view', 'Pool View'), ('park_view', 'Park View'), ('golf_course_view', 'Golf Course View'), ('unblocked_open_view', 'Unblocked Open View'), ('skyline_view', 'Skyline View'), ('river_canal_view', 'River or Canal View'), ('garden_view', 'Garden View'), ('lake_view', 'Lake View')], max_length=30, null=True),
        ),
    ]
