# Generated by Django 4.2.1 on 2023-05-29 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_alter_property_bathrooms_alter_property_bedrooms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='property',
            name='photos',
        ),
    ]
