# Generated by Django 4.2.1 on 2023-05-29 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_property_buildings'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property.project'),
        ),
    ]
