# Generated by Django 4.2.1 on 2023-05-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_property_photo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='unit_view',
            field=models.CharField(blank=True, choices=[('blocked_view', 'Blocked View'), ('360_views', '360° Views'), ('City View', 'City View'), ('pool_view', 'Pool View'), ('park_view', 'Park View'), ('golf_course_view', 'Golf Course View'), ('unblocked_open_view', 'Unblocked Open View'), ('skyline_view', 'Skyline View'), ('river_canal_view', 'River or Canal View'), ('garden_view', 'Garden View'), ('lake_view', 'Lake View')], max_length=30, null=True),
        ),
    ]
