# Generated by Django 4.2.1 on 2023-06-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0022_property_address_property_area_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(max_length=150, null=True)),
                ('about_name', models.CharField(max_length=150, null=True)),
                ('description', models.TextField(null=True)),
                ('photo_name', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
            },
        ),
        migrations.AlterModelOptions(
            name='facilitiescategory',
            options={'verbose_name': 'Facility Category', 'verbose_name_plural': 'Facilities Category'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Condo', 'verbose_name_plural': 'Condos'},
        ),
    ]
