# Generated by Django 4.2.1 on 2023-06-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0023_about_alter_facilitiescategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='green_text',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
