# Generated by Django 4.2.1 on 2023-06-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0024_about_green_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(blank=True, max_length=150, null=True)),
                ('blog_long_name', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(blank=True, max_length=25, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('first_description', models.TextField(blank=True, null=True)),
                ('second_description', models.TextField(blank=True, null=True)),
                ('quote', models.TextField(blank=True, null=True)),
                ('author_quote', models.CharField(blank=True, max_length=50, null=True)),
                ('photo_name', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.ManyToManyField(blank=True, to='property.category')),
                ('tag', models.ManyToManyField(blank=True, to='property.tag')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
    ]
