# Generated by Django 4.2.1 on 2023-06-02 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0026_alter_blog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(blank=True, choices=[('Hot', 'Hot'), ('New', 'New')], max_length=25, null=True),
        ),
    ]
