# Generated by Django 4.2.1 on 2023-06-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0028_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_overview', models.CharField(blank=True, max_length=100, null=True)),
                ('buy_price_first', models.DecimalField(blank=True, decimal_places=1, max_digits=15, null=True)),
                ('buy_price_second', models.DecimalField(blank=True, decimal_places=1, max_digits=15, null=True)),
                ('rent_price_first', models.DecimalField(blank=True, decimal_places=1, max_digits=15, null=True)),
                ('rent_price_second', models.DecimalField(blank=True, decimal_places=1, max_digits=15, null=True)),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('distance_location', models.DecimalField(blank=True, decimal_places=1, max_digits=15, null=True)),
                ('time_location', models.DecimalField(blank=True, decimal_places=1, max_digits=15, null=True)),
                ('buy_nums_properties', models.IntegerField(blank=True, null=True)),
                ('rent_nums_properties', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Overview',
                'verbose_name_plural': 'Overviews',
            },
        ),
    ]
