# Generated by Django 4.2.1 on 2023-06-02 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0029_overview'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='overview_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property.overview'),
        ),
    ]
