# Generated by Django 4.2.1 on 2023-06-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0030_project_overview_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='overview',
            new_name='overview_o',
        ),
        migrations.RemoveField(
            model_name='project',
            name='overview_key',
        ),
        migrations.AddField(
            model_name='overview',
            name='projects',
            field=models.ManyToManyField(blank=True, to='property.project'),
        ),
    ]
