# Generated by Django 4.2.1 on 2023-06-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0032_project_overview_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id_answer', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Overview',
                'verbose_name_plural': 'Overviews',
            },
        ),
        migrations.CreateModel(
            name='ReviewsOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('surname', models.CharField(blank=True, max_length=100, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('maintenance', models.IntegerField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], null=True)),
                ('quality_of_finishing', models.IntegerField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], null=True)),
                ('staff_security', models.IntegerField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], null=True)),
                ('value_for_money', models.IntegerField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], null=True)),
                ('facilities_on_site', models.IntegerField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], null=True)),
                ('location', models.IntegerField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], null=True)),
            ],
            options={
                'verbose_name': 'Overview',
                'verbose_name_plural': 'Overviews',
            },
        ),
        migrations.AddField(
            model_name='overview',
            name='condos',
            field=models.ManyToManyField(blank=True, to='property.property'),
        ),
        migrations.AddField(
            model_name='overview',
            name='latitude',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='overview',
            name='longitude',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='overview',
            name='photo_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='overview',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
