# Generated by Django 4.2.1 on 2023-06-05 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0033_answer_reviewsoverview_overview_condos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overview',
            name='condos',
        ),
    ]
