# Generated by Django 4.2.1 on 2023-06-05 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0034_remove_overview_condos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.AlterModelOptions(
            name='reviewsoverview',
            options={'verbose_name': 'Review Overview', 'verbose_name_plural': 'Reviews Overview'},
        ),
    ]
