# Generated by Django 4.2.1 on 2023-06-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0038_reviewsoverview_overview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overview',
            name='buy_nums_properties',
        ),
        migrations.RemoveField(
            model_name='overview',
            name='rent_nums_properties',
        ),
        migrations.AddField(
            model_name='overview',
            name='airport',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='overview',
            name='distance_airport',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='overview',
            name='time_airport',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=15, null=True),
        ),
    ]
