# Generated by Django 4.2.1 on 2023-06-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0040_answer_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id_answer', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('for_table', models.CharField(blank=True, max_length=100, null=True)),
                ('question', models.CharField(blank=True, max_length=300, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
