# Generated by Django 4.2.1 on 2023-06-05 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0041_question_delete_answer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
