# Generated by Django 4.2.1 on 2023-06-06 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0045_reviewsoverview_average'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewsoverview',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property.project'),
        ),
    ]
