# Generated by Django 4.2.1 on 2023-06-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0046_reviewsoverview_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='completion_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='monthly_rentals',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='year_built',
            field=models.DateField(blank=True, null=True),
        ),
    ]
