# Generated by Django 4.2.1 on 2023-06-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0047_project_completion_status_project_monthly_rentals_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overview',
            name='projects',
        ),
        migrations.AlterField(
            model_name='project',
            name='monthly_rentals',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='for_table',
            field=models.CharField(blank=True, choices=[('Overview', 'Overview'), ('Project', 'Project')], max_length=100, null=True),
        ),
    ]
