# Generated by Django 4.2.1 on 2023-06-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0048_remove_overview_projects_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='completion_status',
            field=models.CharField(blank=True, choices=[('Complited', 'Complited'), ('Not done', 'Not done')], max_length=20, null=True),
        ),
    ]
