# Generated by Django 4.2.1 on 2023-06-07 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0049_alter_project_completion_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'other About', 'verbose_name_plural': 'other About'},
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'other Blog', 'verbose_name_plural': 'other Blogs'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'help Category', 'verbose_name_plural': 'help Categories'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'other Contact', 'verbose_name_plural': 'other Contacts'},
        ),
        migrations.AlterModelOptions(
            name='developer',
            options={'verbose_name': 'main Developer', 'verbose_name_plural': 'main Developers'},
        ),
        migrations.AlterModelOptions(
            name='facilitiescategory',
            options={'verbose_name': 'help Facility Category', 'verbose_name_plural': 'help Facilities Category'},
        ),
        migrations.AlterModelOptions(
            name='overview',
            options={'verbose_name': 'main Overview', 'verbose_name_plural': 'main Overviews'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'main Project', 'verbose_name_plural': 'main Projects'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'main Condo', 'verbose_name_plural': 'main Condos'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'help Question', 'verbose_name_plural': 'help Questions'},
        ),
        migrations.AlterModelOptions(
            name='reviewsoverview',
            options={'verbose_name': 'help Review Overview', 'verbose_name_plural': 'help Reviews Overview'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'other Tag', 'verbose_name_plural': 'other Tags'},
        ),
    ]
