# Generated by Django 4.2.1 on 2023-06-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0051_property_latitude_property_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='map_latitude',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='map_longitude',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='latitude',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='longitude',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
    ]
