# Generated by Django 4.2.1 on 2023-06-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0052_alter_project_map_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='listing_type',
            field=models.CharField(blank=True, choices=[('Sell', 'Sell'), ('Rent', 'Rent'), ('Sell&Rent', 'Sell&Rent')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(blank=True, choices=[('House', 'House'), ('Villa', 'Villa'), ('Condo', 'Condo'), ('Apartment', 'Apartment'), ('Townhouse', 'Townhouse'), ('Land', 'Land'), ('Shophouse', 'Shophouse')], max_length=30, null=True),
        ),
    ]
