# Generated by Django 4.2.1 on 2023-06-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0054_alter_property_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='property_type',
            field=models.CharField(blank=True, choices=[('house', 'House'), ('villa', 'Villa'), ('condo', 'Condo'), ('apartment', 'Apartment'), ('townhouse', 'Townhouse'), ('land', 'Land'), ('shophouse', 'Shophouse')], max_length=30, null=True),
        ),
    ]
