# Generated by Django 4.2.1 on 2023-06-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0056_rename_project_name_property_condo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
