# Generated by Django 4.2.1 on 2023-06-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0058_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='property_features',
        ),
        migrations.AddField(
            model_name='property',
            name='property_features',
            field=models.ManyToManyField(blank=True, to='property.features'),
        ),
    ]
