# Generated by Django 4.2.1 on 2023-06-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0059_remove_property_property_features_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='property_features',
        ),
        migrations.DeleteModel(
            name='Features',
        ),
        migrations.AddField(
            model_name='property',
            name='property_features',
            field=models.TextField(blank=True, null=True),
        ),
    ]
