# Generated by Django 4.2.1 on 2023-06-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0061_property_photo_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='latitude',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='longitude',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
