# Generated by Django 4.2.1 on 2023-06-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0062_alter_property_latitude_alter_property_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='map_latitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='map_longitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
