# Generated by Django 4.2.1 on 2023-06-09 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0063_property_map_latitude_property_map_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='map_latitude',
        ),
        migrations.RemoveField(
            model_name='property',
            name='map_longitude',
        ),
    ]
