# Generated by Django 4.2.1 on 2023-06-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0064_remove_property_map_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_slug',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='developer_slug',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='overview',
            name='overview_slug',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_slug',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_slug',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
