# Generated by Django 4.2.1 on 2023-06-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0067_category_category_slug_tag_tag_slug_alter_blog_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'help Description',
                'verbose_name_plural': 'help Descriptions',
            },
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'main About', 'verbose_name_plural': 'main About'},
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'main Blog', 'verbose_name_plural': 'main Blogs'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'other Category', 'verbose_name_plural': 'other Categories'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'main Contact', 'verbose_name_plural': 'main Contacts'},
        ),
    ]
