# Generated by Django 4.2.1 on 2023-06-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0068_description_alter_about_options_alter_blog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='template',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
