# Generated by Django 4.2.1 on 2023-06-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0071_rename_condo_name_property_property_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='SEO_description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='SEO_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='SEO_description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='SEO_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='overview',
            name='SEO_description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='overview',
            name='SEO_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='SEO_description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='SEO_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='SEO_description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='SEO_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
