# Generated by Django 4.2.1 on 2023-06-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0072_blog_seo_description_blog_seo_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='price_rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='starting_price_rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
