# Generated by Django 4.2.1 on 2023-06-26 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0073_project_price_rent_project_starting_price_rent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewsoverview',
            old_name='facilities_on_site',
            new_name='agent_support',
        ),
        migrations.RenameField(
            model_name='reviewsoverview',
            old_name='maintenance',
            new_name='property_r',
        ),
        migrations.RemoveField(
            model_name='project',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='reviewsoverview',
            name='quality_of_finishing',
        ),
        migrations.RemoveField(
            model_name='reviewsoverview',
            name='staff_security',
        ),
    ]
