# Generated by Django 4.2.1 on 2023-06-27 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0074_rename_facilities_on_site_reviewsoverview_agent_support_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewsoverview',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property.property'),
        ),
    ]
