# Generated by Django 4.2.1 on 2023-06-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0076_rename_price_per_sqm_property_price_per_sqm_rent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewsoverview',
            options={'ordering': ['overview', 'project', 'property'], 'verbose_name': 'help Review Overview', 'verbose_name_plural': 'help Reviews Overview'},
        ),
        migrations.AlterField(
            model_name='property',
            name='furnishing',
            field=models.CharField(blank=True, choices=[('Unfurnished', 'Unfurnished'), ('Fully Furnished', 'Fully Furnished'), ('Partly Furnished', 'Partly Furnished'), ('Bare Shell', 'Bare Shell'), ('Negotiable', 'Negotiable')], max_length=30, null=True),
        ),
    ]
