# Generated by Django 4.2.1 on 2023-06-28 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0077_alter_reviewsoverview_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewsoverview',
            options={'ordering': ['overview__name_overview', 'project__project_name', 'property__property_name'], 'verbose_name': 'help Review Overview', 'verbose_name_plural': 'help Reviews Overview'},
        ),
    ]
