# Generated by Django 4.2.1 on 2023-06-28 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0078_alter_reviewsoverview_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewsoverview',
            options={'verbose_name': 'help Review Overview', 'verbose_name_plural': 'help Reviews Overview'},
        ),
    ]
