# Generated by Django 4.2.1 on 2023-06-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0079_alter_reviewsoverview_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
