# Generated by Django 4.2.1 on 2023-07-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0080_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
