# Generated by Django 4.2.1 on 2023-07-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0081_property_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
