# Generated by Django 4.2.1 on 2023-07-06 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0084_lists'),
    ]

    operations = [
        migrations.AddField(
            model_name='lists',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='lists',
            name='compare_list',
        ),
        migrations.RemoveField(
            model_name='lists',
            name='wish_list',
        ),
        migrations.AddField(
            model_name='lists',
            name='compare_list',
            field=models.ManyToManyField(blank=True, related_name='users_compare_list', to='property.property'),
        ),
        migrations.AddField(
            model_name='lists',
            name='wish_list',
            field=models.ManyToManyField(blank=True, related_name='users_wish_list', to='property.property'),
        ),
    ]
