# Generated by Django 4.2.1 on 2023-07-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0085_lists_user_remove_lists_compare_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lists',
            name='search',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
