# Generated by Django 4.2.1 on 2023-07-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0086_lists_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lists',
            name='search',
            field=models.TextField(blank=True, null=True),
        ),
    ]
