# Generated by Django 4.2.1 on 2023-07-14 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0087_alter_lists_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='lists',
            name='сurrency_switcher',
            field=models.CharField(blank=True, choices=[('US', 'US'), ('AED', 'AED')], max_length=10, null=True),
        ),
    ]
