# Generated by Django 4.2.1 on 2023-07-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0089_alter_lists_сurrency_switcher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lists',
            name='сurrency_switcher',
            field=models.CharField(blank=True, choices=[('AED', 'AED'), ('US', 'US')], default='AED', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='rent_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='sold_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
    ]
